### PR TITLE
feat: Add carousels to landing page and update content

### PR DESCRIPTION
**Pull request by Yinkajay**
This PR...

## Changes

-

## Fixes
-

## Checklist

- [x] tested locally
- [x] added new dependencies
- [ ] updated the docs
- [x] added/updated a component
- [ ] fixed a bug
- [ ] added/updated a new route
- [x] added or changed css styles

Fixes #

### CODE REVIEW

**Review by Boye95 — APPROVED** [review]
Thanks @Yinkajay 🎉

**Review by Boye95 — COMMENTED** [review]
@Yinkajay Could you remove the paganiation dots(buttons) for the hero section's carousel.

**Comment by Yinkajay** [comment]
> @Yinkajay Could you remove the paganiation dots(buttons) for the hero section's carousel.

Alright, will do

**Review by tobisupreme — APPROVED** [review]

**Comment by Boye95** [comment]
> > @Yinkajay Could you remove the paganiation dots(buttons) for the hero section's carousel.
> 
> Alright, will do

Thanks

**Pull request merged**
