### PR TITLE
chore: update jwt-decode export name & removes an unused import

### PR DESCRIPTION
**Pull request by Boye95**
This PR...

## Changes

- removes an unused import
- update jwt-decode export name

## Fixes
-

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [x] added/updated a component
- [ ] fixed a bug
- [ ] added/updated a new route
- [ ] added or changed css styles

Fixes #

### CODE REVIEW

**Review by just-talis — APPROVED** [review]
i actually thought we were using tsx....
this pr is blocked? uhmmm...

**Comment by Boye95** [comment]
> i actually thought we were using tsx.... this pr is blocked? uhmmm...

Can you explain what you mean by ```this pr is blocked``` and the TSX migration has been put on hold for now.
@just-talis

**Review by just-talis — APPROVED** [review]

**Comment by just-talis** [comment]
> > i actually thought we were using tsx.... this pr is blocked? uhmmm...
> 
> Can you explain what you mean by `this pr is blocked` and the TSX migration has been put on hold for now. @just-talis

Don’t worry, i read something else, mistake...

**Comment by Boye95** [comment]
Okay. Thanks 🚀

**Review by tobisupreme — APPROVED** [review]

**Pull request merged**
